# Generated by Django 3.1.5 on 2021-12-31 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narro_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomment',
            name='comment_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='post_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
